### PR TITLE
Fix baselines.py

### PR DESCRIPTION
**Pull request by JustinKavalan**
This pull requests address issue #15 (which was related to corrupt files / time data mismatch) by throwing out corrupt files when being loaded.

Any help in testing master and code revisions/suggestions are appreciated.

### CODE REVIEW

**Comment by JustinKavalan** [comment]
From the old pr: https://github.com/mdeff/fma/pull/42

> Thanks for the PR! It was a poor decision of mine to mix up the code for the creation of an hypothetical next release and the maintenance of the usage code and doc for the latest released version. I've now corrected this mistake and made two branches: `master` works with the latest released data (i.e., rc1) and `next` contains code to prepare a next release. More at #41.
> 
> I've tried to rebase your modifications on top of master but made a wrong manipulation that closed the PR and removed my right to edit. :/
> 
> Can you reopen it, and base your changes on the current master? It should then work with the publicly available rc1 data. :)

I went ahead and rebased the commits, but I won't be able to get around to testing it / cleaning up unnecessary changes in baselines.py until this weekend. In the meantime, let me know if there are any comments that need to be addressed

**Comment by mdeff** [comment]
BTW, are the corrupted files part of [the list of files shorter than 30s](https://github.com/mdeff/fma/wiki#excerpts-shorter-than-30s-and-erroneous-audio-length-metadata)?

**Comment by JustinKavalan** [comment]
Yeah once it was all migrated over to utils.py is redundant (although I do suggest enabling autoreload, this allow you run the import cell again if something goes wrong on an import). I'm running reverted baselines.py to the one in mdeff:master, but it seems to be erroring on too many files (see output below). Yeah most if not all of the files I saw earlier were the files shorter than 30s, there might've been couple others too. Most of the ones below aren't those files though.

<details>
<summary>Output</summary>

```
Ignoring /Users/justin/Downloads/fma_small/148/148633.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/148/148633.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/057/057403.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/057/057403.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Epoch 1/20
Ignoring /Users/justin/Downloads/fma_small/022/022093.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/057/057441.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/057/057441.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/018/018145.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/004/004072.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/001/001682.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/107/107105.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/107/107105.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/033/033542.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/033/033542.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/148/148584.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/054/054561.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/054/054561.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/033/033119.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/033/033119.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/142/142412.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/142/142412.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/015/015176.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/015/015176.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/093/093862.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/093/093862.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/080/080229.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/080/080229.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/065/065175.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/065/065175.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/134/134625.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/134/134625.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/148/148960.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/148/148960.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/146/146967.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/146/146967.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/071/071871.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/071/071871.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/079/079790.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/079/079790.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/026/026024.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/026/026024.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/137/137896.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/125/125697.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/125/125697.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/071/071313.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/071/071313.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/078/078297.mp3 (error: Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/078/078297.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1.).
Ignoring /Users/justin/Downloads/fma_small/119/119941.mp3 (error: Audio data must be floating-point).
Ignoring /Users/justin/Downloads/fma_small/010/010577.mp3 (error: Audio data must be floating-point).
```
</details>

**Comment by JustinKavalan** [comment]
Just figured out my environment, it appears to be working properly! Although I haven't seen any skipped files, which is odd. I'll let it run overnight

**Comment by mdeff** [comment]
Thanks for testing. I didn't test myself (I was only editing on my laptop). The change I made in 09481c3226110754f95d7620819e232e3b3c10dc should not impact which files are skipped (exceptions are caught as you did). I wanted to avoid to reallocate `self.X` and `self.Y` with `np.delete`. Memory is allocated in `__init__` and `__next__` fills them (overwriting past data).

> It also does not seem to be loading samples during the epochs after an initial batch of epochs.

What do you mean?

Looking at `FfmpegLoader`, I think it could error for files with a sampling rate different from 44.1 kHz.

**Comment by JustinKavalan** [comment]
Hm yeah I definitely agree with your changes, and I also am not sure where some of this behavior is coming from. 

Basically, there'll be a batch of errors at the beginning and then that would be the entirety of the output. For example, I let baselines.py run overnight and what I attached above is ALL of the output from the night.

Although I'm also running this on my laptop (I have since shut down my gcp instance) so it might be related to the environment. I'll run my old code that I know works and compare the behavior tonight to see if it's something related to that.

**Comment by mdeff** [comment]
Weird. Thanks. Maybe there's something we miss from your old code.

**Comment by JustinKavalan** [comment]
Okay there were some idiosyncrasies stemming from my python version (3.6) and so I downgraded to python 3.5 and it seems to be working properly now. I had to change the print statement to support python3.5.

I also remembered that we toyed around with the architecture a bit in baselines.py and got the accuracy up to 35%. Should I commit those changes as well?

**Comment by mdeff** [comment]
TensorFlow 1.0.1 has a [`manylinux1` wheel for python 3.6](https://pypi.org/project/tensorflow/1.0.1/#files). And it should work, as I developed this code with python 3.6. Or maybe you're not using linux? Anyway I'm fine with a 3.5-compatible `print`.

> Also, the issue with the FFmpeg errors was caused because I forgot to set this line `subset = tracks.index[tracks['set', 'subset'] <= 'medium']` to `<= 'small'`. Perhaps this should be documented a little bit more?

Do you mean that there are no errors with `small`? Are the errors with `medium` due to you having only downloaded `fma_small.zip`, hence missing many tracks from `medium`?

> I also remembered that we toyed around with the architecture a bit in baselines.py and got the accuracy up to 35%. Should I commit those changes as well?

Please do as long as it's a simple architecture (`baselines.ipynb` is supposed to be a demo). But in a separate PR. ;)

**Comment by JustinKavalan** [comment]
> And it should work, as I developed this code with python 3.6. Or maybe you're not using linux? Anyway I'm fine with a 3.5-compatible print.

Ah yeah I'm not on Linux

> Do you mean that there are no errors with small? Are the errors with medium due to you having only downloaded fma_small.zip, hence missing many tracks from medium?

There are errors with small, but most of them are just the ones from the "list of files shorter than 30s". But also yes, the errors I was getting when this was set to medium are the tracks that are in medium but not in small.

> Please do as long as it's a simple architecture (baselines.ipynb is supposed to be a demo). But in a separate PR. ;)

Yeah it was mostly just a couple of fully connected layers added on the end, wasn't too bad at all.

As far as this goes, I think this is ready for a merge but I'll leave that with you as the repository owner.

**Comment by mdeff** [comment]
Thanks for providing the reported errors.

1. Errors due to tracks [known to be shorter than 30s](https://github.com/mdeff/fma/wiki#excerpts-shorter-than-30s-and-erroneous-audio-length-metadata):
    ```
    fma_small/099/099134.mp3 => Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/099/099134.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1 => track of length 0s
    fma_small/108/108925.mp3 => Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/108/108925.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1 => track of length 0s
    fma_small/133/133297.mp3 => Command '['ffmpeg', '-i', '/Users/justin/Downloads/fma_small/133/133297.mp3', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '22050', '-']' returned non-zero exit status 1 => track of length 0s
    fma_small/098/098565.mp3 => could not broadcast input array from shape (13,139) into shape (13,2582) => track of length 1.6s
    fma_small/098/098567.mp3 => could not broadcast input array from shape (13,44) into shape (13,2582) => track of length 0.5s
    fma_small/098/098569.mp3 => could not broadcast input array from shape (13,132) into shape (13,2582) => track of length 1.5s
    ```
2. Errors due to tracks falling short of 1 MFCC:
    ```
    fma_small/017/017631.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/017/017634.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/017/017635.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/017/017636.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/017/017637.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/054/054576.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/054/054578.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    fma_small/055/055783.mp3 => could not broadcast input array from shape (13,2581) into shape (13,2582)
    ```

The second kind of errors could be eliminated by truncating a bit (i.e., allowing a safety margin). Do you have by any chance the errors returned by the `FfmpegLoader(sampling_rate=2000)` (section 2.1) and `FfmpegLoader(sampling_rate=16000)` (section 2.2) (the current ones are for `MfccLoader()`, section 3.1)?

**Comment by mdeff** [comment]
> Yeah it was mostly just a couple of fully connected layers added on the end, wasn't too bad at all.

Looking forward to a separate PR then. :)

**Review by mdeff — APPROVED** [review]
Thanks!

**Pull request merged**
